### PR TITLE
Changed coretypes to use a defined size for bus word lengths

### PR DESCRIPTION
**Pull request by jbendes**

### CODE REVIEW

**Comment by olsoni** [comment]
I'm having a hard time conceptualizing how this allows zcm to work on a system where sizeof(int16_t) = 1 (or rather, more importantly, where an int8_t is 16 bits). To me it seems like the encode / decode would still run into issues because you are memcpy-ing into a int8_t buffer, which will be the wrong size in bits.

**Comment by olsoni** [comment]
it's also worth noting that the `__string_encoded_array_size` function (around line 713) was already making assumptions about the size of particular types of data. We should definitely change that to use the `#define` values

**Comment by jbendes** [comment]
Yeah so it took me a while to wrap my head around it too. But essentially the end result is this: a 16 bit uint8 machine would never have a buffer of 8 bit uint8s from receipt of a message. It would have already been converted into a 16bit uint8 array when read by the transport. So serial, for example, would read only 8 bit words, but it would read them into a 16bit word buffer leaving half the word empty (zero filled). That way by the time it hits core types it's already in a memcpy-able format.

I think the reason why our last attempt at this was so much more complicated is because we were actually putting it into a shared block of memory. Memory that was addressed in 8 bit increments by one CPU and 16bit increments by the other CPU. Which is really weird and hard to address. This doesn't address it

**Comment by olsoni** [comment]
Ok I think I'm on board with that then (would be very interested in seeing some tests on the system in question). Take a peak at thing from https://github.com/ZeroCM/zcm/pull/229#issuecomment-450745572 but then I'd say go ahead and merge (as we've mentioned, this literally can't hurt normal systems).

**Comment by jbendes** [comment]
Yeah I haven't looked at the file yet but I think I know what you're talking about. Will take a look as soon as I get to a computer

**Pull request merged**
