### PR TITLE
WIP: Deb packaging

### PR DESCRIPTION
**Pull request by erniejunior**
maybe this is interesting for you? It makes it tremendously easier to install ZCM on debian based systems.

### CODE REVIEW

**Comment by erniejunior** [comment]
I greatly simplified the travis build script. All the system setup instructions are now condensed in a fairly short `before_install` section (no `install-deps.sh` needed). The idea was that concise build setup instructions double as documentation for anybody who would like to reproduce the build environment.
The changes being made in the `feature/ressurect_old_tests` branch will still need to be added to this.

I also added a deploy section which automatically generates new releases on github with the .deb file. If you merge this you need to modify this section first:
1. Set `deploy.on.branch` to 'master`
1. Set `deploy.api_key.secure` to your encrypted API key. See [here](https://docs.travis-ci.com/user/encryption-keys/) for instructions on how to encrypt it.

**Comment by erniejunior** [comment]
@olsoni @jbendes bump bump. 
I updated this PR to the newest master state and fixed it so it would be awesome if you could merge now. See my post above for instructions on how to properly set up the deploy section or remove it if you do not need it.

**Comment by jbendes** [comment]
@erniejunior For some reason i didn't get notified about this! Will take a look shortly and try it get it merged on master asap!

**Comment by jbendes** [comment]
Hey @erniejunior just took a look and it looks great! We can always iterate later if we need to make improvements. I've updated the creds and travis file. I can't seem to get travis to build though. Not sure how it was working for you. I also rebased on top of master. Take a look if you don't mind and let me know your thoughts.

**Comment by jbendes** [comment]
replaced with #299

**Pull request closed without merging**
