### PR TITLE
Resurrect old tests

### PR DESCRIPTION
**Pull request by erniejunior**
~~Still work in progress.~~ Feel free to add comments and suggestions on how to proceed.
Related to #245

### CODE REVIEW

**Comment by erniejunior** [comment]
I think most work is done now. I would love to hear your feedback @olsoni and @jbendes to get this merged soon so I can rebase the other PR.

**Comment by jbendes** [comment]
Hey @erniejunior so we ran out of time today (we're exhausted haha) to look at this one. Will hopefully get to it this week, but hopefully this one won't slow you down too much on other progress. Let us know if it does and we'll reprioritize

**Comment by erniejunior** [comment]
Don't worry. After you merged the two other open PRs, this one probably needs some love again before it is ready to merge. So if you quickly close the other two rather soonish I can rework this one and we get together later this week.

**Comment by erniejunior** [comment]
@jbendes @olsoni now would be a good time to look at this PR. I merged with the master (sorry but rebasing turned out to be a mess) and adapted the tests to the most recent API changes. They all pass and I intregrated them into the travis script.

**Comment by erniejunior** [comment]
@jbendes @olsoni Bump

**Comment by jbendes** [comment]
Totally missed this thanks for the bump. Isaac and I are out of town this week but will be back next week and can take a look. Is that okay timing?

**Comment by erniejunior** [comment]
sure thanks!

**Comment by erniejunior** [comment]
@jbendes @olsoni are you OK or hit by one of your drones? :worried:

**Comment by jbendes** [comment]
Haha it's been a..........hectic week.......... Hoping to get to this tomorrow or over the weekend. Didn't forget about you June/July are always long months for us haha.

**Comment by jbendes** [comment]
Sorry this weekend isn't happening either. Isaac is on his honeymoon. Next week should slow down tremendously.

**Comment by erniejunior** [comment]
This are priorities that I can relate to ... best wishes to @olsoni

**Comment by olsoni** [comment]
Thanks for your patience, I'm finally getting back around to this after the wedding ...

I've rebased the branch and pushed up a version here. I wanted to change the wscripting around a bit so I undid some of your changes but the version I've pushed up is working for building the examples (and the tests should be a simple extension of that structure). The original way you had it (I believe) could have the potential of building / linking the examples to the wrong version of the libraries if you make changes to both the examples & core code at the same time. This new way is a bit more explicit: it *should* work by just having you run `./waf build_examples` after you've built and installed the primary codebase. There are still 1 or 2 hiccups that I'll want to look over with @jbendes, but I think they are relatively minor. 

I only skimmed the conversion of the tests to cxxtests briefly, but I was able to build and run them once and it seemed like it was working well. That's a great step and will make it a lot easier to validate stuff.

**Comment by erniejunior** [comment]
Hi, thanks a lot for reviewing the code! Do I understand correctly, that building the examples is now considered a variant? Do I understand correctly that with
> and the tests should be a simple extension of that structure

means that the tests should also become a variant? If so are you going to do this or should I do it? I am looking forward to merge soon then.

**Comment by olsoni** [comment]
Yeah I should have a chance to add a "tests" variant this weekend.

**Comment by erniejunior** [comment]
Awesome!

**Comment by olsoni** [comment]
Ok tests are building now (build_tests) and I added the cxxtest runner to the travis install. Travis build is failing now because a couple of the tests don't pass when run under asan (probably just leaked memory). 

I'd like @jbendes to take a look at the build changes and then we should also run through the actual tests. @erniejunior I know you ported the old tests to cxxtests (though potentially deleted the udpm_high_rate_multifrag.c one?), but given that the tests were kinda in the attic for a while, I'd bet they could use an update.

**Comment by erniejunior** [comment]
Hi @olsoni thanks a lot for the test build rework! I pulled your changes into my branch but for me the CI fails for other reasons. Maybe some hiccup during merging? Would you mind working in my PR branch (I made sure you have write access) so I can also see the travis output (if you work on your own internal branch I can see the code changes but not travis builds)?

Unfortunately it is now too long ago for me to remember what happened with `udpm_high_rate_multifrag.c` ...

I too think, that the old tests are just a base to start from to do more throughout tests.

**Pull request merged**
