### PR TITLE
Add publishRaw method to python wrap

### PR DESCRIPTION
**Pull request by Sid1057**
Add raw publish method to python wrap. It was helpful for me when I wrote custom log analyzer for my task. So I think this method in python could be helpful for somebody else.

### CODE REVIEW

**Comment by jbendes** [comment]
What exactly was the debugging you were trying to do that required this function be exposed?

**Comment by Sid1057** [comment]
> What exactly was the debugging you were trying to do that required this function be exposed?

Sorry for the late reply. 
I had a task to play our zcm logfile and pause publishing after each message from some channel with the name set by a user. By the conditions, I haven't information about data types of messages in playing log. My solution was a python script which read events from zcm log, compares channel with the user channel and publish the message. If the name of a current message channel name is equal to the user channel name, I pause my script. For publishing message of unknown class, I have to publish it using publishRaw method, which was not implemented in python wrap.
Anyway, this function exists in cpp API, so I think it wouldn't be a bad thing to provide programmer more freedom for developing flexible soft.

**Comment by jbendes** [comment]
I must have missed your response! Sorry about that. Have you taken a look at `zcm-logplayer-gui`? It has exactly the functionality you just described. You simply type in a channel prefix into the text box in the lower right hand corner and click "step"

**Comment by Sid1057** [comment]
@jbendes yes, but there is at least one important condition why I couldn't use `zcm-logplayer-gui`: I need to implement it as a script without gui. The first idea was to use `zcm-logplayer`, but it hasn't this functionality.

**Comment by jbendes** [comment]
That makes total sense. Sorry I got pulled away from this for a bit. Mind rebasing it on top of master?

**Comment by Sid1057** [comment]
> That makes total sense. Sorry I got pulled away from this for a bit. Mind rebasing it on top of master?
@jbendes It's ok. Yes, thank you.

**Comment by jbendes** [comment]
Just pushed up a branch that I believe addresses this entirely. Mind taking a look and letting me know if it satisfies your requirements?

**Comment by jbendes** [comment]
Should be handled in https://github.com/ZeroCM/zcm/pull/243

**Pull request closed without merging**
