### PR TITLE
Give names to the handler/sender/receiver threads

### PR DESCRIPTION
**Pull request by Duam**
Referring to issue ZeroCM/zcm#211

### CODE REVIEW

**Comment by jbendes** [comment]
So the suffix "_np" in function you used `pthread_setname_np` stands for "non posix". That means that the function isn't available on all posix systems. So unfortunately we'd have to find a way around that. We can either `#ifdef` guard it somehow if we're able to find a `#define` that signifies that the function is available, or perhaps there is another way to name a thread?

**Comment by jbendes** [comment]
Ahhh yeah looks like you're right. Must have been mis-remembering. That's fine for now, we can address it under the rule of 3 (once we have 2 more examples of platform specific stuff)

**Comment by jbendes** [comment]
Would you mind rebasing this branch on top of `master`? Makes a nice and clean git branch

**Comment by Duam** [comment]
> I'm also testing this branch right now and when i run `zcm-spy-lite` and open `htop` in another terminal, I still only see `zcm-spy-lite` listed a bunch of times

That's weird. After applying the changes I went through the installation instructions (configure, build, install) again and it showed me the correct output.

(my try at copying htop output)
PID | Command
------------ | -------------
3554 | zcm-spy-lite -p /usr/local/lib ...
3557 | - ZeroCM_receiver
3556 | - zcm-spy-lite
3555 | - ZeroCM_handler

I'm not sure what the thread 3556 does, but it makes sense that it doesn't have a sender thread.

**Comment by jbendes** [comment]
Very weird. I'm unable to get it to htop to say that. I've tried a  `./waf distclean` and then full recompile of everything but still nothing. Wonder what i'm doing wrong.........

What system are you testing on?

**Comment by Duam** [comment]
I am using Ubuntu 18.04.1 LTS. 
What is your htop output? I noticed that htop's search via `F4` is quite rigid. It only shows you exactly the threads with the desired names, even when there are other threads attached to the process. For example, when searching for `zcm-spy-lite` it would only show you this:

PID | Command
------------ | -------------
3554 | zcm-spy-lite -p /usr/local/lib ...
3556 | - zcm-spy-lite

If this is your output, try searching for the process manually (with tree-view via `F5`).

**Comment by jbendes** [comment]
Very bizarre. Maybe it's my computer but I am unable to replicate these results. Wonder if it's the difference between 16.04 and 18.04. Have you tried this on 16.04?

**Comment by jbendes** [comment]
Yeah this doesn't seem to work on Amazon Linux either. I haven't yet tested 18.04. Have you tested this on any other system?

**Comment by jbendes** [comment]
:man_facepalming: 
I didn't know about F2 haha. All looks good on my end! Can you reset this pullreq to `origin/Duam-thread_names`? It's just a rebased and reviewed version of your branch. Thanks for the patience haha

**Comment by Duam** [comment]
No problem :sweat_smile: I did as you requested and I hope everything is good now.

**Comment by Duam** [comment]
No problem :sweat_smile: I did as you requested and I hope everything is good now.

**Comment by Duam** [comment]
No problem :sweat_smile: I did as you requested and I hope everything is good now.

**Comment by jbendes** [comment]
Hmmm looks like you did a bit of a weird rebase/merge. I just put up a new [pullreq](https://github.com/ZeroCM/zcm/pull/221) with what I meant. Will merge it in as soon as travis is done building.

**Comment by Duam** [comment]
Great thanks! And sorry for the mess. Just for feedback: What should I have done instead? For the next time I create a pull-request.

**Pull request closed without merging**
