### PR TITLE
Add python packaging support for python2 and 3

### PR DESCRIPTION
**Pull request by erniejunior**
We build and install using pip2/pip3 now which is being triggered by the waf build.

We need to build the python bindings *after* installing zcm because otherwise the zcm library won't be found during the python build.

### CODE REVIEW

**Comment by erniejunior** [comment]
Travis build fails since zcm is not installed globally I guess? I am calling ldconfig to make the zcm c library findable but apparently cython can't find it.

**Comment by jbendes** [comment]
Give me 5 minutes. I'm just updating some stuff and then I can take a look for you

**Comment by jbendes** [comment]
Hmm I'm not sure I follow what's going on. What exactly is the issue? It looks like cython isn't running properly?

**Comment by jbendes** [comment]
Also, if you wouldn't mind rebasing on top of the newest master, that'd be great. Just had to do some cleanup as we made a mistake with merge order last week

**Comment by jbendes** [comment]
I'm not sure I'm following. I just took a look at your changes and it doesn't look like you're quite using waf the way is intended. Can you explain what you're trying to do here? Waf treats build and install as two different steps. It looks like you're trying to install during the build step? You also won't have sudo permission to run your `ldconfig` during build but not sure why you're doing that anyway.  As for python2 vs python3, we'll have to add command line waf options to allow the user to specify which one they want to build.

**Comment by jbendes** [comment]
Also, any dependencies needed to build the repo should be placed in `zcm/scripts/install-deps.sh`.

**Comment by erniejunior** [comment]
I have to admit, that the waf documentation is a bit unclear, but please read more about the feature I used [here](https://waf.io/book/#_more_build_options). The confusing thing about this part of the documentation, that the text and example code contradict each other:

The text states, that using `ctx.add_post_fun` you would add a function that is executed after the **build** has finished.
The code example below, executes a special command (in this case ldconfig, like I did) after the **install** has finished.
Here is the code example for clarity:
```python
top = '.'
out = 'build'

def options(ctx):
        ctx.add_option('--exe', action='store_true', default=False,
                help='execute the program after it is built')

def configure(ctx):
        pass

def pre(ctx): 1
        print('before the build is started')

def post(ctx):
        print('after the build is complete')
        if ctx.cmd == 'install':
                if ctx.options.exe:
                        ctx.exec_command('/sbin/ldconfig')

def build(ctx):
        ctx.add_pre_fun(pre)
        ctx.add_post_fun(post)
```

What actually happens in the code example is this: using `ctx.add_post_fun(post)` the previously defined function `post` is registered as a post function. This way, waf will execute it after the build phase **and** after the install phase. Inside the `post` function, there is a check if this time its the install phase (`if ctx.cmd == 'install'`) and if so, it executes ldconfig.

*Some background concerning ldconfig:* It updates the library cache of your system. You need to call it once after you installed a new library (which we do when we install libzcm.so), otherwise the linker won't find it (the alternative would be to log out and log back in).

**Comment by jbendes** [comment]
Sorry I'll clarify my questions:

1) It seems that you are manually installing some dependencies in `.travis.yml` instead of in the `./scripts/install-deps.sh` file. I think you probably want to do it in the `install-deps.sh` file.
2) Waf splits its build up into 3 steps, `configure`, `build`, and `install`. We need to be building the python bindings in that format. It looks like you're doing the `build` and `install` during waf's `install` step and ignoring the `PREFIX` specified during config. Waf knows about where the files are getting installed.
3) Additionally, your python building doesn't use or depend on any waf nodes (files in the repo). Therefore it won't be tracked properly when files get changed. You probably want to emulate what's happening in other wscripts that do similar custom build/install steps. Take a look at `zcm/zcm/wscript` near line `42-60` to see an entry point into a custom function that properly depends on a file in the repo

**Comment by jbendes** [comment]
I'm going to just close out this pullreq. We should be transitioning fully to python 3 by the end of the year anyway so I see no reason to support building both 2.7 and 3 at the same time. Feel free to reopen if you disagree

**Pull request closed without merging**
