### PR TITLE
API housekeeping

### PR DESCRIPTION
**Pull request by erniejunior**
I opened this PR just to kick of travis CI to make sur all my commits work for all targets. Comments and reviews are welcome but this is work in progress. In here I implement on what we agreed in #249 .

### CODE REVIEW

**Comment by olsoni** [comment]
@erniejunior 

We went through the branch and cleaned up the API a bunch. Kept the updated construction syntax & returns and added a few extra error code returns where they weren't present yet. We did revert some of the changes to "try" functions (like flush & (un)subscribe) but clarified that those functions actually only exist for use in language-specific bindings where the threading architecture does not allow you to call the vanilla variants. We also took another pass at the ZCM_EMBEDDED ifndefs and think we settled on something that we like (keeping unnecessary comparisons down as well as avoiding compiler warnings). 

We're ready to merge as is and have run through all the examples to verify they are working. Take a peak & let us know what you think.

**Comment by erniejunior** [comment]
Wow this are a lot of useful additions! I especially like the removal of errno.
The only whish I could have is to get the return code back on zcm_stop() and the C++ equivalent. Why did you decide to remove it?
If really do not like it then go ahead and close the PR (I can live with it) but it would be nice to have it.

**Comment by jbendes** [comment]
@erniejunior the reason why stop no longer has a return code is because it there is nothing to return. When you call `zcm.stop()`, zcm will be stopped when that function call returns.

**Comment by jbendes** [comment]
Let me know if you're good to merge and I'll merge it

**Comment by erniejunior** [comment]
Then please merge.

**Pull request merged**
